### ISSUE TITLE
Streaming iterators

### ISSUE THREAD

**Issue by rhn** [vhdirk/notmuch-rs#16]
Hi,

since there's no official mailing list for the project, please excuse the choice of place.

I have just noticed that the API for messages access changed a lot, with StreamingIterator being in use now. I'm guessing this is to get some speedup?

The change is kind of problematic, since the StreamingIterator doesn't implement any normal Iterator interfaces, and there aren't any examples. That makes the crate so much less useful if consumers have to reinvent the wheel. I'm wondering what the benchmarks say - I have personally not seen notmuch-rs as the bottleneck.

Cheers

**Comment by vhdirk** [comment]
The goal of these changes was to make it easier for developers to work with it. In my application, I had a hard time managing the (stack) lifetimes of the objects, which is even more annoying given that they actually just contain pointers to data on the heap.

So I've been looking for a way to improve that, because rental or owningref were really cluttering my application. This is where SuperCow came in, as it gives you the ability to work with either stack lifetimes, or parent-owning handles. The cost in both memory and performance seemed minimal enough compared to the flexibility it provides.

At the same time, I've been solving various issues regarding pointer lifetimes. Notmuch's documentation states that a message is owned by the messages iterator, and you can't build such lifetime dependencies with the regular iterator trait. Hence StreamingIterator.

However, notmuch's documentation is sometimes unclear when it comes to lifetime, and currently notmuch-rs is destroying messages too quickly and too strict with regard to who owns it. Some tests I wrote made it clear that the messages iterator does not actually own the individual messages. They are owned by the thread or query, meaning that StreamingIterator may likely go away again.

**Comment by rhn** [comment]
I think that it's a good idea to stick to what the library says when they expose a certain interface - ownership may be an implementation detail, and that can go away with a minor bump.

That being said, I spent the last 2 hours trying to get Message objects into a vector and I failed miserably. The lifetime mess coming from StreamingIterator is really hard to manage, and I don't think I still understand more than a tiny bit. I tried implementing a trait that would collect all the messages into a Vec, but that didn't quite work. Flexibility would be nice, but at the moment it's not there for me ;)

**Comment by rhn** [comment]
By the way, is your code online somewhere?

**Comment by vhdirk** [comment]
>I think that it's a good idea to stick to what the library says when they expose a certain interface - ownership may be an implementation detail, and that can go away with a minor bump.

True, yet to be sure I contacted the devs on the mailing list for this.

I'm co-developing notmuch-rs with enamel: https://github.com/vhdirk/enamel. It's not much yet, but it may help you to understand how to use notmuch-rs in its current form.

**Comment by rhn** [comment]
I gave it a bit more thought, and I'm going to give the new version a pass for now. The API is complex, so my main hurdle is the lack of docs and examples. I'd have to spend a block of couple of hours to learn it, and currently I don't have that. As long as my stuff works with 0.2.1, I'll stick to that one. But when the situation changes, I'm happy to contribute to master again.

**Comment by vhdirk** [comment]
@rhn I've just pushed a commit the 'lifetimes' branch. Since the iterators in notmuch don't actually have any ownership over the items, ```StreamingIterator``` (and ```StreamingIteratorExt```) has been removed again.
That way, it should be closer to 0.2.1 (but with more correct ownership rules).
I have to write more tests and example code before I'm merging this into master.

**Comment by rhn** [comment]
On Fri, 14 Dec 2018 09:55:21 -0800
Dirk Van Haerenborgh <notifications@github.com> wrote:

> @rhn I've just pushed a commit the 'lifetimes' branch. Since the iterators in notmuch don't actually have any ownership over the items, ```StreamingIterator``` (and ```StreamingIteratorExt```) has been removed again.
> That way, it should be closer to 0.2.1 (but with more correct ownership rules).
> I have to write more tests and example code before I'm merging this into master.
> 

Thank you - if it's close enough to 0.2.1, then I'll contribute docs/tests/examples as I adjust my code.

**Comment by rhn** [comment]
I tried to use the branch, but even after applying https://github.com/vhdirk/notmuch-rs/pull/20 , it doesn't compile with lifetime problems:

```
error[E0309]: the parameter type `O` may not live long enough                
  --> /foo/notmuch-rs/src/filenames.rs:32:5          
   |                                                                         
27 | pub struct Filenames<'o, O>                                             
   |                          - help: consider adding an explicit lifetime bound `O: 'o`...
...                                                                          
32 |     pub(crate) marker: ScopedPhantomcow<'o, O>,                         
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          
   |                                                                         
note: ...so that the type `O` will meet its required lifetime bounds         
  --> /foo/notmuch-rs/src/filenames.rs:32:5          
   |                                                                         
32 |     pub(crate) marker: ScopedPhantomcow<'o, O>,                         
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vhdirk** [comment]
Do you have an example of what you're trying to do? I have some time to work on this today.

**Comment by rhn** [comment]
I tried to build the lifetimes branch, after reverting the 2018 change. One attempt is at https://github.com/rhn/notmuch-rs/tree/borked

**Comment by vhdirk** [comment]
@rhn: see the 'develop' branch. It 's now pre-1028

**Comment by rhn** [comment]
Thanks, that works. I'm going to spend some time updating my code now and will come back with impressions/contributions.

**Comment by rhn** [comment]
The develop branch almost works perfectly and with almost no effort, but it has a fatal flaw: it's no longer possible to recursively traverse messages (at first glance). Here's the bug I encountered:

https://github.com/vhdirk/notmuch-rs/commit/f1f571da6e996f596742e2b9575f8823da880811

```
$ cargo test
   Compiling notmuch v0.4.2 (/foo/quemail/notmuch-rs)        
warning: unused import: `NonSyncFeatures`                                    
 --> src/utils.rs:4:43                                                       
  |                                                                          
4 | use supercow::{Supercow, DefaultFeatures, NonSyncFeatures};              
  |                                           ^^^^^^^^^^^^^^^                
  |                                                                          
  = note: #[warn(unused_imports)] on by default                              
                                                                             
warning: unused import: `NonSyncFeatures`                                    
 --> src/utils.rs:4:43                                                       
  |                                                                          
4 | use supercow::{Supercow, DefaultFeatures, NonSyncFeatures};              
  |                                           ^^^^^^^^^^^^^^^                
  |                                                                          
  = note: #[warn(unused_imports)] on by default                              
                                                                             
warning: unused import: `Threads`                                            
 --> tests/main.rs:6:32                                                      
  |                                                                          
6 | use notmuch::{Query, QueryExt, Threads};                                 
  |                                ^^^^^^^                                   
  |                                                                          
  = note: #[warn(unused_imports)] on by default                              
                                                                             
error: reached the recursion limit while instantiating `messages::tests::descend::<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<query::Query>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>, messages::Messages<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<message::Message<query::Query>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>`
   --> src/messages.rs:113:5                                                 
    |                                                                        
113 | /     fn descend<'o, O: 'o + super::MessageOwner, T: Iterator<Item=super::Message<'o, O>>>(iter: T)
114 | |             -> usize {                                               
115 | |         iter.map(|msg| descend(msg.replies()) ).count()              
116 | |     }                                                                
    | |_____^                                                                
                                                                             
error: aborting due to previous error                                        
                                                                             
error: Could not compile `notmuch`.
```

I'm not sure how to solve it yet.

**Comment by vhdirk** [comment]
It's another issues with lifetimes. I've been experimenting some more over the weekend: It seems every ```Thread``` and ```Message``` should actually only be bound to the ```Query```. That way, there's no need for this kind of nesting. ```Filenames``` and ```Directory``` are linked to each ```Message```.
I'd like to come up with a solution soon.

The biggest difficulty here is that sharing a ```Phantomcow``` would require a mutable reference to ```self```, which is an odd requirement when you want to call ```Message::replies()```

**Comment by rhn** [comment]
>  It seems every Thread and Message should actually only be bound to the Query

I believe the only call that can make this kind of nesting (or at the very least the one sufficient) is the `Message::reply()`, which always returns NULL if the message doesn't come from a Thread. I'm working on a solution right now, but I'm slowing down as I'm deep diving into Supercow, which I don't understand at all yet. If you'd like to have a real time chat, I'm on #rust on the Mozilla IRC for the next couple of hours.

**Comment by rhn** [comment]
Bombs away: I submitted the patch explicitly stating what happens to the list from `get_replies()`. I expect that even if they don't want to have this guarantee, some other workable one will get hashed out.

We'll probably have to send more patches regarding tags, filenames etc.

It would be nice if anyone interested replies to make it clear that this is an important issue.

**Comment by vhdirk** [comment]
My last commits on develop link the ownership of ```replies``` to the owner of the ```Message``` itself, without requiring a mutable reference to ```Message``` to begin with. I think tests may be needed for this one.

**Comment by vhdirk** [comment]
Fixed in 0.5.0
